### PR TITLE
Moves near-duplicate detection functionality to NearDuplicatesIndex clas...

### PR DESCRIPTION
**Pull request by gusaaaaa**
This commit:
- Refactors Detector class, moving near-duplicate detection functionality to NearDuplicatesIndex class. This allows to separate document representation from its location (until now, documents could only be loaded from the filesystem).
- Tests NearDuplicatesIndex functionality.
- Removes Detector's test, since it wasn't accomplishing its objective.

Motivation behind these changes:
- I had the requirement to calculate near duplicates among html documents, building the index on the fly, and without being able to store the documents in the filesystem.

### CODE REVIEW

**Comment by parkr** [comment]
Shit dude, this is great! Thanks! How did you discover this project?

**Comment by gusaaaaa** [comment]
I just searched "near duplicates" and filtered by "python" :)

**Comment by parkr** [comment]
Awesome, glad my code could be of help to you. This refactor produces all the results you're looking for, yeah?

**Comment by gusaaaaa** [comment]
so far, yes. would you like to merge it with master branch?

**Comment by parkr** [comment]
I would love to. Thanks man!

**Comment by parkr** [comment]
If you find this useful, do you want to maintain the repo with me?

**Comment by gusaaaaa** [comment]
sure!

**Comment by parkr** [comment]
Done!

**Pull request merged**
